<a href="https://colab.research.google.com/github/robsongrego/Pos_graduacao_puc/blob/main/Aulas_1_a_3_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Aula 01 - NumPy (Arrays) + Introdução ao Git

Documentação do Numpy: https://numpy.org/doc/stable/user/index.html

Então vamos instalar essa bagaça!

In [ ]:
pip install numpy

Por que utilizar o NumPy no lugar de listas?

In [ ]:
import numpy as np

lista_notas = [3.4, 5.6, 7.8, 0.2, 5.6, 8.4, 1.5]

# for nota in lista_notas:
#   nota += 1

# Acessando posição por posição da lista e alterando diretamente nela
# for i in range(len(lista_notas)):
#   lista_notas[i] += 1

# for i, _ in enumerate(lista_notas):
#   lista_notas[i] += 1

# Sobrescrevendo a variável original com uma nova lista alterada com base na original
# lista_notas = [nota + 1 for nota in lista_notas]

print(lista_notas)
print(type(lista_notas))

lista_notas = np.array(lista_notas)

print(lista_notas)
print(type(lista_notas))

lista_notas += 1

lista_notas *= 2

lista_notas /= 1.8

# Todas as operações matemáticas agora podem ser feitas diretamente na variável que guarda o ndarray (+, -, *, /, **)
# lista_notas[3] += 1

print(lista_notas)

[3.4, 5.6, 7.8, 0.2, 5.6, 8.4, 1.5]
<class 'list'>
[3.4 5.6 7.8 0.2 5.6 8.4 1.5]
<class 'numpy.ndarray'>
[ 4.88888889  7.33333333  9.77777778  1.33333333  7.33333333 10.44444444
  2.77777778]




Eu consigo somar duas listas?

In [ ]:
lista_notas_extra = [0.2, 0.7, 0.3, 0.7, 0.7, 0]

# Aqui estou simplesmente printando o resultado da operação e não sobrescrevendo o array original
print(lista_notas + lista_notas_extra)

# O código acima resulta em erro, pois os operandos tem tamanhos diferentes
print(lista_notas - lista_notas_extra)
print(lista_notas * lista_notas_extra)
print(lista_notas)


ValueError: ignored

Como eu faço pra inicializar um array já sabendo o tamanho dele?

In [ ]:
lista_notas_extra = [0.3] * len(lista_notas)
lista_notas_extra = np.full(len(lista_notas), 0.3)
lista_notas_extra2 = np.zeros(len(lista_notas))
lista_notas_extra3 = np.ones(len(lista_notas))
print(lista_notas_extra)
print(lista_notas_extra2)
print(lista_notas_extra3)

print("\n")
print("Número de dimensões:", np.ndim(lista_notas_extra3))
print("Número de elementos em cada dimensão:", np.shape(lista_notas_extra3))
print("\n")

# Aqui estou simplesmente printando o resultado da operação e não sobrescrevendo o array original
print(lista_notas + lista_notas_extra)

# O código acima resulta em erro, pois os operandos tem tamanhos diferentes
print(lista_notas - lista_notas_extra)
print(lista_notas * lista_notas_extra)
print(lista_notas)


[0.3 0.3 0.3 0.3 0.3 0.3 0.3]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


Número de dimensões: 1
Número de elementos em cada dimensão: (7,)


[ 5.18888889  7.63333333 10.07777778  1.63333333  7.63333333 10.74444444
  3.07777778]
[ 4.58888889  7.03333333  9.47777778  1.03333333  7.03333333 10.14444444
  2.47777778]
[1.46666667 2.2        2.93333333 0.4        2.2        3.13333333
 0.83333333]
[ 4.88888889  7.33333333  9.77777778  1.33333333  7.33333333 10.44444444
  2.77777778]


Okay, mas eu quero começar a filtrar o conteúdo do meu array...

In [ ]:
for nota in lista_notas:
  if nota > 6:
    print(nota)

print(lista_notas > 6)
filtro = lista_notas > 6 # condição lógica

# Quando eu quiser filtrar o conteúdo do meu array com base em uma comparação, eu aplico a seguinte sintaxe
print(lista_notas[filtro])

7.333333333333333
9.777777777777779
7.333333333333333
10.444444444444445
[False  True  True False  True  True False]
[ 7.33333333  9.77777778  7.33333333 10.44444444]


Mas eu quero aplicar mais de uma condição, e agora?

In [ ]:
# filtro_faixa = 6 < lista_notas < 9 -> esta linha dá ruim, porque esta operação conjunta não foi implementada para o ndarray
# filtro_faixa = lista_notas > 6 and lista_notas < 9 -> esta linha também dá ruim...
filtro_faixa = (lista_notas > 6) & (lista_notas < 9) # and
print(filtro_faixa)
print(lista_notas[filtro_faixa])

lista_notas_final = np.array([7, 6, 7, 8, 6, 7, 5])
filtro_faixa = (lista_notas > 5) | (lista_notas_final >= 7) # or
print(filtro_faixa)
print(lista_notas[filtro_faixa])

# Aula 02 - NumPy (Arrays/Matrix/Tensor)

Vamos imaginar que temos um array de notas de um único aluno...

In [ ]:
array_aluno = np.array([6.7, 3.2, 8.5])
print(array_aluno)

[6.7 3.2 8.5]


Mas e se tivéssemos mais de um alunos?

In [ ]:
matrix_alunos = np.array([
    [6.7, 3.2, 8.5],
    [3.1, 3.7, 2.6],
    [8.7, 9.1, 7.4],
    [0.2, 0, 2],
])
print(matrix_alunos)
print(type(matrix_alunos))

lista_alunos = [6.7, 3.2, 8.5, 3.1, 3.7, 2.6, 8.7, 9.1, 7.4, 0.2, 0, 2,]
matrix_alunos = np.array(lista_alunos).reshape(4, 3)
print(matrix_alunos)

print(matrix_alunos * 1.2)
# print(matrix_alunos + [0.5, 0.3, 0, 0.2]) -> Não funciona, pois precisa ter o mesmo tamanho da segunda dimensão da matriz
print(matrix_alunos + [0.5, 0.3, 0])

[[6.7 3.2 8.5]
 [3.1 3.7 2.6]
 [8.7 9.1 7.4]
 [0.2 0.  2. ]]
<class 'numpy.ndarray'>
[[6.7 3.2 8.5]
 [3.1 3.7 2.6]
 [8.7 9.1 7.4]
 [0.2 0.  2. ]]
[[ 8.04  3.84 10.2 ]
 [ 3.72  4.44  3.12]
 [10.44 10.92  8.88]
 [ 0.24  0.    2.4 ]]
[[7.2 3.5 8.5]
 [3.6 4.  2.6]
 [9.2 9.4 7.4]
 [0.7 0.3 2. ]]


Não gostei, eu quero que as provas sejam as linhas e os alunos as colunas...

In [ ]:
matrix_alunos_transposta = np.array([
    # [6.7, 3.2, 8.5],
    # [3.1, 3.7, 2.6],
    # [8.7, 9.1, 7.4],
    # [0.2, 0, 2],
    [6.7, 3.1, 8.7, 0.2], # P1
    [3.2, 3.7, 9.1, 0], # P2
    [8.5, 2.6, 7.4, 2], # P3
])
print(matrix_alunos_transposta)
print(matrix_alunos.T)
print(matrix_alunos)

print("Acessando a segunda nota do terceiro aluno:", matrix_alunos[2][1])
print("Acessando a segunda nota do terceiro aluno:", matrix_alunos[2, 1])
print("Acessando a segunda nota do terceiro aluno:", matrix_alunos.T[1][2])
print("Acessando a segunda nota do terceiro aluno:", matrix_alunos.T[1, 2])

pesos_array = np.array([2, 3, 4])
print(pesos_array)
print(matrix_alunos * [2, 3, 4])

produto_escalar = matrix_alunos @ pesos_array # soma das notas multiplicadas pelos seus respectivos pesos
# produto_escalar = matrix_alunos.dot(pesos_array) # soma das notas multiplicadas pelos seus respectivos pesos
print(produto_escalar)

soma_dos_pesos = pesos_array.sum()
# print(sum(pesos_array))
media_dos_alunos = produto_escalar/soma_dos_pesos
print('Média da turma:', media_dos_alunos.sum()/4)

media_da_turma = produto_escalar.sum()/(pesos_array.sum() * 4)
print('Média da turma:', media_da_turma)

print(matrix_alunos.T.sum()) # Somamos todos os valores da matriz
print(matrix_alunos.T.sum(axis=1)) # Somamos os valores da matriz por linha
print(matrix_alunos.T.sum(axis=0)) # Somamos os valores da matriz por coluna

print(matrix_alunos.mean()) # Média de todos os valores da matriz
print(matrix_alunos.mean(axis=1)) # Média para cada linha da matriz
print(matrix_alunos.mean(axis=0)) # Média para cada coluna da matriz

print(matrix_alunos.min(axis=1)) # A menor nota dentre as notas de cada aluno
print(matrix_alunos.max()) # A maior nota dentre todas as notas
print(matrix_alunos.mean(axis=1).max()) # A maior média dentre os alunos

[[6.7 3.1 8.7 0.2]
 [3.2 3.7 9.1 0. ]
 [8.5 2.6 7.4 2. ]]
[[6.7 3.1 8.7 0.2]
 [3.2 3.7 9.1 0. ]
 [8.5 2.6 7.4 2. ]]
[[6.7 3.2 8.5]
 [3.1 3.7 2.6]
 [8.7 9.1 7.4]
 [0.2 0.  2. ]]
Acessando a segunda nota do terceiro aluno: 9.1
Acessando a segunda nota do terceiro aluno: 9.1
Acessando a segunda nota do terceiro aluno: 9.1
Acessando a segunda nota do terceiro aluno: 9.1
[2 3 4]
[[13.4  9.6 34. ]
 [ 6.2 11.1 10.4]
 [17.4 27.3 29.6]
 [ 0.4  0.   8. ]]
[57.  27.7 74.3  8.4]
Média da turma: 4.6499999999999995
Média da turma: 4.65
55.199999999999996
[18.7 16.  20.5]
[18.4  9.4 25.2  2.2]
4.6
[6.13333333 3.13333333 8.4        0.73333333]
[4.675 4.    5.125]
[3.2 2.6 7.4 0. ]
9.1
8.399999999999999


AttributeError: ignored

Relizando operações aritméticas:

Mas e se tivéssemos cada aluno com múltiplas disciplinas?

Agora é pra quem gosta de matemática!


Pra quem gosta de álgebra linear, vamos imaginar uma matriz de pesos e uma matriz de alunos por disciplinas, sendo o conteúdo a média do aluno naquela disciplina:

ATIVIDADE DE FIXAÇÃO 1

- Criar um array bidimensional com dados diferentes dos utilizados em sala;
- Obter dados estatísticos (pelo menos 3, uma com axis=1, a outra com axis = 0 e a última sem axis);
- Obter a transposta da matriz e realizar uma operação com ela
- Realizar um produto escalar entre duas matrizes ou de um array com uma matriz
- Criar um filtro para a sua matriz
- Realizar alguma operação aritmética (número com matriz, array com matriz, etc.)

OBS.: Entregar pelo gitlab

EXTRA (200XP): Os dados devem vir de algum arquivo externo.